development:
  adapter: postgresql
  encoding: unicode
  database: satinder_gensys_development
  pool: 5
  timeout: 5000
  username: satinder
  password: satinder123
test:
  adapter: postgresql
  encoding: unicode
  database: satinder_gensys_development 
  pool: 5
  timeout: 5000
  username: satinder
  password: satinder123

production:
  adapter: postgresql
  encoding: unicode
  database: satinder_gensys_development
  pool: 5
  timeout: 5000
  username: satinder
  password: satinder123
